const matches = [
    // MATCHDAY 1
    {id:1,team1:{name:"Mexico",flag:"🇲🇽"},team2:{name:"South Africa",flag:"🇿🇦"},date:"Jun 11 — Mexico City",group:"Group A",result:"2-0"},
    {id:2,team1:{name:"South Korea",flag:"🇰🇷"},team2:{name:"Czechia",flag:"🇨🇿"},date:"Jun 11 — Zapopan",group:"Group A",result:"2-1"},
    {id:3,team1:{name:"Canada",flag:"🇨🇦"},team2:{name:"Bosnia",flag:"🇧🇦"},date:"Jun 12 — Toronto",group:"Group B",result:"1-1"},
    {id:4,team1:{name:"USA",flag:"🇺🇸"},team2:{name:"Paraguay",flag:"🇵🇾"},date:"Jun 12 — Los Angeles",group:"Group D",result:"4-1"},
    {id:5,team1:{name:"Qatar",flag:"🇶🇦"},team2:{name:"Switzerland",flag:"🇨🇭"},date:"Jun 13 — Santa Clara",group:"Group B",result:"1-1"},
    {id:6,team1:{name:"Brazil",flag:"🇧🇷"},team2:{name:"Morocco",flag:"🇲🇦"},date:"Jun 13 — New Jersey",group:"Group C",result:"1-1"},
    {id:7,team1:{name:"Haiti",flag:"🇭🇹"},team2:{name:"Scotland",flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿"},date:"Jun 13 — Boston",group:"Group C",result:"0-1"},
    {id:8,team1:{name:"Australia",flag:"🇦🇺"},team2:{name:"Turkiye",flag:"🇹🇷"},date:"Jun 14 — Vancouver",group:"Group D",result:"2-0"},
    {id:9,team1:{name:"Germany",flag:"🇩🇪"},team2:{name:"Curacao",flag:"🇨🇼"},date:"Jun 14 — Houston",group:"Group E",result:"7-1"},
    {id:10,team1:{name:"Netherlands",flag:"🇳🇱"},team2:{name:"Japan",flag:"🇯🇵"},date:"Jun 14 — Dallas",group:"Group F",result:"2-2"},
    {id:11,team1:{name:"Ivory Coast",flag:"🇨🇮"},team2:{name:"Ecuador",flag:"🇪🇨"},date:"Jun 14 — Philadelphia",group:"Group E",result:"TBD"},
    {id:12,team1:{name:"Sweden",flag:"🇸🇪"},team2:{name:"Tunisia",flag:"🇹🇳"},date:"Jun 14 — Monterrey",group:"Group F",result:"TBD"},
    {id:13,team1:{name:"Spain",flag:"🇪🇸"},team2:{name:"Cabo Verde",flag:"🇨🇻"},date:"Jun 15 — Atlanta",group:"Group H",result:"TBD"},
    {id:14,team1:{name:"Belgium",flag:"🇧🇪"},team2:{name:"Egypt",flag:"🇪🇬"},date:"Jun 15 — Seattle",group:"Group G",result:"TBD"},
    {id:15,team1:{name:"Saudi Arabia",flag:"🇸🇦"},team2:{name:"Uruguay",flag:"🇺🇾"},date:"Jun 15 — Miami",group:"Group H",result:"TBD"},
    {id:16,team1:{name:"Iran",flag:"🇮🇷"},team2:{name:"New Zealand",flag:"🇳🇿"},date:"Jun 15 — Los Angeles",group:"Group G",result:"TBD"},
    {id:17,team1:{name:"France",flag:"🇫🇷"},team2:{name:"Senegal",flag:"🇸🇳"},date:"Jun 16 — New Jersey",group:"Group I",result:"TBD"},
    {id:18,team1:{name:"Iraq",flag:"🇮🇶"},team2:{name:"Norway",flag:"🇳🇴"},date:"Jun 16 — Boston",group:"Group I",result:"TBD"},
    {id:19,team1:{name:"Argentina",flag:"🇦🇷"},team2:{name:"Algeria",flag:"🇩🇿"},date:"Jun 16 — Kansas City",group:"Group J",result:"TBD"},
    {id:20,team1:{name:"Austria",flag:"🇦🇹"},team2:{name:"Jordan",flag:"🇯🇴"},date:"Jun 17 — Santa Clara",group:"Group J",result:"TBD"},
    {id:21,team1:{name:"Portugal",flag:"🇵🇹"},team2:{name:"DR Congo",flag:"🇨🇩"},date:"Jun 17 — Houston",group:"Group K",result:"TBD"},
    {id:22,team1:{name:"England",flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿"},team2:{name:"Croatia",flag:"🇭🇷"},date:"Jun 17 — Dallas",group:"Group L",result:"TBD"},
    {id:23,team1:{name:"Ghana",flag:"🇬🇭"},team2:{name:"Panama",flag:"🇵🇦"},date:"Jun 17 — Toronto",group:"Group L",result:"TBD"},
    {id:24,team1:{name:"Uzbekistan",flag:"🇺🇿"},team2:{name:"Colombia",flag:"🇨🇴"},date:"Jun 17 — Mexico City",group:"Group K",result:"TBD"},
    // MATCHDAY 2
    {id:25,team1:{name:"Czechia",flag:"🇨🇿"},team2:{name:"South Africa",flag:"🇿🇦"},date:"Jun 18 — Atlanta",group:"Group A",result:"TBD"},
    {id:26,team1:{name:"Mexico",flag:"🇲🇽"},team2:{name:"South Korea",flag:"🇰🇷"},date:"Jun 18 — Zapopan",group:"Group A",result:"TBD"},
    {id:27,team1:{name:"Switzerland",flag:"🇨🇭"},team2:{name:"Bosnia",flag:"🇧🇦"},date:"Jun 18 — Los Angeles",group:"Group B",result:"TBD"},
    {id:28,team1:{name:"Canada",flag:"🇨🇦"},team2:{name:"Qatar",flag:"🇶🇦"},date:"Jun 18 — Vancouver",group:"Group B",result:"TBD"},
    {id:29,team1:{name:"USA",flag:"🇺🇸"},team2:{name:"Australia",flag:"🇦🇺"},date:"Jun 19 — Seattle",group:"Group D",result:"TBD"},
    {id:30,team1:{name:"Scotland",flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿"},team2:{name:"Morocco",flag:"🇲🇦"},date:"Jun 19 — Boston",group:"Group C",result:"TBD"},
    {id:31,team1:{name:"Brazil",flag:"🇧🇷"},team2:{name:"Haiti",flag:"🇭🇹"},date:"Jun 19 — Philadelphia",group:"Group C",result:"TBD"},
    {id:32,team1:{name:"Turkiye",flag:"🇹🇷"},team2:{name:"Paraguay",flag:"🇵🇾"},date:"Jun 19 — Santa Clara",group:"Group D",result:"TBD"},
    {id:33,team1:{name:"Netherlands",flag:"🇳🇱"},team2:{name:"Sweden",flag:"🇸🇪"},date:"Jun 20 — Houston",group:"Group F",result:"TBD"},
    {id:34,team1:{name:"Germany",flag:"🇩🇪"},team2:{name:"Ivory Coast",flag:"🇨🇮"},date:"Jun 20 — Toronto",group:"Group E",result:"TBD"},
    {id:35,team1:{name:"Ecuador",flag:"🇪🇨"},team2:{name:"Curacao",flag:"🇨🇼"},date:"Jun 20 — Kansas City",group:"Group E",result:"TBD"},
    {id:36,team1:{name:"Tunisia",flag:"🇹🇳"},team2:{name:"Japan",flag:"🇯🇵"},date:"Jun 21 — Monterrey",group:"Group F",result:"TBD"},
    {id:37,team1:{name:"Spain",flag:"🇪🇸"},team2:{name:"Saudi Arabia",flag:"🇸🇦"},date:"Jun 21 — Atlanta",group:"Group H",result:"TBD"},
    {id:38,team1:{name:"Belgium",flag:"🇧🇪"},team2:{name:"Iran",flag:"🇮🇷"},date:"Jun 21 — Los Angeles",group:"Group G",result:"TBD"},
    {id:39,team1:{name:"Uruguay",flag:"🇺🇾"},team2:{name:"Cabo Verde",flag:"🇨🇻"},date:"Jun 21 — Miami",group:"Group H",result:"TBD"},
    {id:40,team1:{name:"New Zealand",flag:"🇳🇿"},team2:{name:"Egypt",flag:"🇪🇬"},date:"Jun 21 — Vancouver",group:"Group G",result:"TBD"},
    {id:41,team1:{name:"Argentina",flag:"🇦🇷"},team2:{name:"Austria",flag:"🇦🇹"},date:"Jun 22 — Dallas",group:"Group J",result:"TBD"},
    {id:42,team1:{name:"France",flag:"🇫🇷"},team2:{name:"Iraq",flag:"🇮🇶"},date:"Jun 22 — Philadelphia",group:"Group I",result:"TBD"},
    {id:43,team1:{name:"Norway",flag:"🇳🇴"},team2:{name:"Senegal",flag:"🇸🇳"},date:"Jun 22 — New Jersey",group:"Group I",result:"TBD"},
    {id:44,team1:{name:"Jordan",flag:"🇯🇴"},team2:{name:"Algeria",flag:"🇩🇿"},date:"Jun 22 — Santa Clara",group:"Group J",result:"TBD"},
    {id:45,team1:{name:"Portugal",flag:"🇵🇹"},team2:{name:"Uzbekistan",flag:"🇺🇿"},date:"Jun 23 — Houston",group:"Group K",result:"TBD"},
    {id:46,team1:{name:"England",flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿"},team2:{name:"Ghana",flag:"🇬🇭"},date:"Jun 23 — Boston",group:"Group L",result:"TBD"},
    {id:47,team1:{name:"Panama",flag:"🇵🇦"},team2:{name:"Croatia",flag:"🇭🇷"},date:"Jun 23 — Toronto",group:"Group L",result:"TBD"},
    {id:48,team1:{name:"Colombia",flag:"🇨🇴"},team2:{name:"DR Congo",flag:"🇨🇩"},date:"Jun 23 — Zapopan",group:"Group K",result:"TBD"},
    // MATCHDAY 3
    {id:49,team1:{name:"Switzerland",flag:"🇨🇭"},team2:{name:"Canada",flag:"🇨🇦"},date:"Jun 24 — Vancouver",group:"Group B",result:"TBD"},
    {id:50,team1:{name:"Bosnia",flag:"🇧🇦"},team2:{name:"Qatar",flag:"🇶🇦"},date:"Jun 24 — Seattle",group:"Group B",result:"TBD"},
    {id:51,team1:{name:"Scotland",flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿"},team2:{name:"Brazil",flag:"🇧🇷"},date:"Jun 24 — Miami",group:"Group C",result:"TBD"},
    {id:52,team1:{name:"Morocco",flag:"🇲🇦"},team2:{name:"Haiti",flag:"🇭🇹"},date:"Jun 24 — Atlanta",group:"Group C",result:"TBD"},
    {id:53,team1:{name:"Czechia",flag:"🇨🇿"},team2:{name:"Mexico",flag:"🇲🇽"},date:"Jun 24 — Mexico City",group:"Group A",result:"TBD"},
    {id:54,team1:{name:"South Africa",flag:"🇿🇦"},team2:{name:"South Korea",flag:"🇰🇷"},date:"Jun 24 — Monterrey",group:"Group A",result:"TBD"},
    {id:55,team1:{name:"Curacao",flag:"🇨🇼"},team2:{name:"Ivory Coast",flag:"🇨🇮"},date:"Jun 25 — Philadelphia",group:"Group E",result:"TBD"},
    {id:56,team1:{name:"Ecuador",flag:"🇪🇨"},team2:{name:"Germany",flag:"🇩🇪"},date:"Jun 25 — New Jersey",group:"Group E",result:"TBD"},
    {id:57,team1:{name:"Japan",flag:"🇯🇵"},team2:{name:"Sweden",flag:"🇸🇪"},date:"Jun 25 — Dallas",group:"Group F",result:"TBD"},
    {id:58,team1:{name:"Tunisia",flag:"🇹🇳"},team2:{name:"Netherlands",flag:"🇳🇱"},date:"Jun 25 — Kansas City",group:"Group F",result:"TBD"},
    {id:59,team1:{name:"Turkiye",flag:"🇹🇷"},team2:{name:"USA",flag:"🇺🇸"},date:"Jun 25 — Los Angeles",group:"Group D",result:"TBD"},
    {id:60,team1:{name:"Paraguay",flag:"🇵🇾"},team2:{name:"Australia",flag:"🇦🇺"},date:"Jun 25 — Santa Clara",group:"Group D",result:"TBD"},
    {id:61,team1:{name:"Norway",flag:"🇳🇴"},team2:{name:"France",flag:"🇫🇷"},date:"Jun 26 — Boston",group:"Group I",result:"TBD"},
    {id:62,team1:{name:"Senegal",flag:"🇸🇳"},team2:{name:"Iraq",flag:"🇮🇶"},date:"Jun 26 — Toronto",group:"Group I",result:"TBD"},
    {id:63,team1:{name:"Cabo Verde",flag:"🇨🇻"},team2:{name:"Saudi Arabia",flag:"🇸🇦"},date:"Jun 26 — Houston",group:"Group H",result:"TBD"},
    {id:64,team1:{name:"Uruguay",flag:"🇺🇾"},team2:{name:"Spain",flag:"🇪🇸"},date:"Jun 26 — Zapopan",group:"Group H",result:"TBD"},
    {id:65,team1:{name:"Egypt",flag:"🇪🇬"},team2:{name:"Iran",flag:"🇮🇷"},date:"Jun 26 — Seattle",group:"Group G",result:"TBD"},
    {id:66,team1:{name:"New Zealand",flag:"🇳🇿"},team2:{name:"Belgium",flag:"🇧🇪"},date:"Jun 26 — Vancouver",group:"Group G",result:"TBD"},
    {id:67,team1:{name:"Panama",flag:"🇵🇦"},team2:{name:"England",flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿"},date:"Jun 27 — New Jersey",group:"Group L",result:"TBD"},
    {id:68,team1:{name:"Croatia",flag:"🇭🇷"},team2:{name:"Ghana",flag:"🇬🇭"},date:"Jun 27 — Philadelphia",group:"Group L",result:"TBD"},
    {id:69,team1:{name:"Algeria",flag:"🇩🇿"},team2:{name:"Austria",flag:"🇦🇹"},date:"Jun 27 — Kansas City",group:"Group J",result:"TBD"},
    {id:70,team1:{name:"Jordan",flag:"🇯🇴"},team2:{name:"Argentina",flag:"🇦🇷"},date:"Jun 27 — Dallas",group:"Group J",result:"TBD"},
    {id:71,team1:{name:"Uzbekistan",flag:"🇺🇿"},team2:{name:"Portugal",flag:"🇵🇹"},date:"Jun 27 — Houston",group:"Group K",result:"TBD"},
    {id:72,team1:{name:"DR Congo",flag:"🇨🇩"},team2:{name:"Colombia",flag:"🇨🇴"},date:"Jun 27 — Atlanta",group:"Group K",result:"TBD"}
];
